import fs from "node:fs";
import path from "node:path";

const files = [
  [
    "flat_001__.gitignore",
    ".gitignore",
    420
  ],
  [
    "flat_002__dot_openai__hosting.json",
    ".openai/hosting.json",
    420
  ],
  [
    "flat_003__README.md",
    "README.md",
    420
  ],
  [
    "flat_004__app__catchall_slug__page.tsx",
    "app/[...slug]/page.tsx",
    420
  ],
  [
    "flat_005__app__chatgpt-auth.ts",
    "app/chatgpt-auth.ts",
    420
  ],
  [
    "flat_006__app__globals.css",
    "app/globals.css",
    420
  ],
  [
    "flat_007__app__layout.tsx",
    "app/layout.tsx",
    420
  ],
  [
    "flat_008__app__page.tsx",
    "app/page.tsx",
    420
  ],
  [
    "flat_009__app__site.tsx",
    "app/site.tsx",
    420
  ],
  [
    "flat_010__build__sites-vite-plugin.ts",
    "build/sites-vite-plugin.ts",
    420
  ],
  [
    "flat_011__db__index.ts",
    "db/index.ts",
    420
  ],
  [
    "flat_012__db__schema.ts",
    "db/schema.ts",
    420
  ],
  [
    "flat_013__drizzle.config.ts",
    "drizzle.config.ts",
    420
  ],
  [
    "flat_014__drizzle__meta___journal.json",
    "drizzle/meta/_journal.json",
    420
  ],
  [
    "flat_015__eslint.config.mjs",
    "eslint.config.mjs",
    420
  ],
  [
    "flat_016__examples__d1__app__api__notes__route.ts",
    "examples/d1/app/api/notes/route.ts",
    420
  ],
  [
    "flat_017__examples__d1__db__schema.ts",
    "examples/d1/db/schema.ts",
    420
  ],
  [
    "flat_018__next.config.ts",
    "next.config.ts",
    420
  ],
  [
    "flat_019__postcss.config.mjs",
    "postcss.config.mjs",
    420
  ],
  [
    "flat_020__public__favicon.svg",
    "public/favicon.svg",
    420
  ],
  [
    "flat_021__public__file.svg",
    "public/file.svg",
    420
  ],
  [
    "flat_022__public__globe.svg",
    "public/globe.svg",
    420
  ],
  [
    "flat_023__public__images__accessible-transport.jpg",
    "public/images/accessible-transport.jpg",
    420
  ],
  [
    "flat_024__public__images__advisor-couple.jpg",
    "public/images/advisor-couple.jpg",
    420
  ],
  [
    "flat_025__public__images__african-american-family.jpg",
    "public/images/african-american-family.jpg",
    420
  ],
  [
    "flat_026__public__images__business-meeting.jpg",
    "public/images/business-meeting.jpg",
    420
  ],
  [
    "flat_027__public__images__charity-box.jpg",
    "public/images/charity-box.jpg",
    420
  ],
  [
    "flat_028__public__images__classroom-students.jpg",
    "public/images/classroom-students.jpg",
    420
  ],
  [
    "flat_029__public__images__community-event.jpg",
    "public/images/community-event.jpg",
    420
  ],
  [
    "flat_030__public__images__community-team.jpg",
    "public/images/community-team.jpg",
    420
  ],
  [
    "flat_031__public__images__donation-sorting.jpg",
    "public/images/donation-sorting.jpg",
    420
  ],
  [
    "flat_032__public__images__family-couch.jpg",
    "public/images/family-couch.jpg",
    420
  ],
  [
    "flat_033__public__images__family-home.jpg",
    "public/images/family-home.jpg",
    420
  ],
  [
    "flat_034__public__images__family-learning.jpg",
    "public/images/family-learning.jpg",
    420
  ],
  [
    "flat_035__public__images__father-children.jpg",
    "public/images/father-children.jpg",
    420
  ],
  [
    "flat_036__public__images__food-support.jpg",
    "public/images/food-support.jpg",
    420
  ],
  [
    "flat_037__public__images__lee-wallace.jpg",
    "public/images/lee-wallace.jpg",
    420
  ],
  [
    "flat_038__public__images__mobility-scooter.jpg",
    "public/images/mobility-scooter.jpg",
    420
  ],
  [
    "flat_039__public__images__modern-apartments.jpg",
    "public/images/modern-apartments.jpg",
    420
  ],
  [
    "flat_040__public__images__modern-campus.jpg",
    "public/images/modern-campus.jpg",
    420
  ],
  [
    "flat_041__public__images__modern-housing.jpg",
    "public/images/modern-housing.jpg",
    420
  ],
  [
    "flat_042__public__images__outreach.jpg",
    "public/images/outreach.jpg",
    420
  ],
  [
    "flat_043__public__images__partner-meeting.jpg",
    "public/images/partner-meeting.jpg",
    420
  ],
  [
    "flat_044__public__images__senior-care.jpg",
    "public/images/senior-care.jpg",
    420
  ],
  [
    "flat_045__public__images__senior-home-help.jpg",
    "public/images/senior-home-help.jpg",
    420
  ],
  [
    "flat_046__public__images__senior-writing.jpg",
    "public/images/senior-writing.jpg",
    420
  ],
  [
    "flat_047__public__images__students-exam.jpg",
    "public/images/students-exam.jpg",
    420
  ],
  [
    "flat_048__public__images__support-elder.jpg",
    "public/images/support-elder.jpg",
    420
  ],
  [
    "flat_049__public__images__teacher-classroom.jpg",
    "public/images/teacher-classroom.jpg",
    420
  ],
  [
    "flat_050__public__images__team-discussion.jpg",
    "public/images/team-discussion.jpg",
    420
  ],
  [
    "flat_051__public__images__team-smiling.jpg",
    "public/images/team-smiling.jpg",
    420
  ],
  [
    "flat_052__public__images__team-table.jpg",
    "public/images/team-table.jpg",
    420
  ],
  [
    "flat_053__public__images__tech-classroom.jpg",
    "public/images/tech-classroom.jpg",
    420
  ],
  [
    "flat_054__public__images__technology-support.jpg",
    "public/images/technology-support.jpg",
    420
  ],
  [
    "flat_055__public__images__training.jpg",
    "public/images/training.jpg",
    420
  ],
  [
    "flat_056__public__images__veteran-community.jpg",
    "public/images/veteran-community.jpg",
    420
  ],
  [
    "flat_057__public__images__veteran-flag.jpg",
    "public/images/veteran-flag.jpg",
    420
  ],
  [
    "flat_058__public__images__volunteer-distribution.jpg",
    "public/images/volunteer-distribution.jpg",
    420
  ],
  [
    "flat_059__public__images__volunteer-wheelchair.jpg",
    "public/images/volunteer-wheelchair.jpg",
    420
  ],
  [
    "flat_060__public__images__wheelchair-support.jpg",
    "public/images/wheelchair-support.jpg",
    420
  ],
  [
    "flat_061__public__uss-logo.svg",
    "public/uss-logo.svg",
    420
  ],
  [
    "flat_062__public__uss-monogram.svg",
    "public/uss-monogram.svg",
    420
  ],
  [
    "flat_063__public__uss-primary-logo.svg",
    "public/uss-primary-logo.svg",
    420
  ],
  [
    "flat_064__public__window.svg",
    "public/window.svg",
    420
  ],
  [
    "flat_065__scripts__build-verified.sh",
    "scripts/build-verified.sh",
    493
  ],
  [
    "flat_066__scripts__install-ci.sh",
    "scripts/install-ci.sh",
    493
  ],
  [
    "flat_067__scripts__sites-env.sh",
    "scripts/sites-env.sh",
    493
  ],
  [
    "flat_068__scripts__validate-artifact.sh",
    "scripts/validate-artifact.sh",
    493
  ],
  [
    "flat_069__tests__rendered-html.test.mjs",
    "tests/rendered-html.test.mjs",
    420
  ],
  [
    "flat_070__tests__site-audit.test.mjs",
    "tests/site-audit.test.mjs",
    420
  ],
  [
    "flat_071__tsconfig.json",
    "tsconfig.json",
    420
  ],
  [
    "flat_072__vite.config.ts",
    "vite.config.ts",
    420
  ],
  [
    "flat_073__worker__index.ts",
    "worker/index.ts",
    420
  ]
];
const root = process.cwd();
let restored = 0;
for (const [flat, target, mode] of files) {
  const src = path.join(root, flat);
  const dest = path.join(root, target);
  if (!fs.existsSync(src)) throw new Error(`Missing flat package file: ${flat}`);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
  if (mode) { try { fs.chmodSync(dest, mode); } catch {} }
  restored++;
}
console.log(`Restored ${restored} project files from the flat GitHub package.`);
